INSERT INTO journals (name, abbreviation, source_type, priority, category, url, update_frequency, keywords_filter, issn) VALUES
('Journal of Memory and Language', 'JML', 'journal', 'P0', '心理语言学核心', 'https://www.sciencedirect.com/journal/journal-of-memory-and-language', '月刊', 'language comprehension,language production,memory,psycholinguistics', '0749-596X'),
('Cognition', NULL, 'journal', 'P0', '认知科学综合', 'https://www.sciencedirect.com/journal/cognition', '月刊', 'cognitive psychology,language,reasoning', '0010-0277'),
('Cognitive Psychology', 'Cognitive Psychology', 'journal', 'P0', '认知心理学核心', 'https://www.sciencedirect.com/journal/cognitive-psychology', '8期/年', 'cognitive processes,language,learning', '0010-0285'),
('Psychological Review', 'Psychol Rev', 'journal', 'P1', '心理学综论', 'https://www.apa.org/pubs/journals/rev', '季刊', 'theoretical psychology,language,cognition', '0033-295X'),
('Language, Cognition and Neuroscience', 'LCN', 'journal', 'P1', '语言与神经', 'https://www.tandfonline.com/toc/plcp21/current', '10期/年', 'language processing,neuroscience,cognitive science', '2327-3798'),
('Psychonomic Bulletin & Review', 'Psychon Bull Rev', 'journal', 'P1', '实验心理学', 'https://link.springer.com/journal/13423', '双月刊', 'cognitive psychology,language,memory', '1069-9384'),
('Cortex', 'Cortex', 'journal', 'P1', '认知神经', 'https://www.sciencedirect.com/journal/cortex', '月刊', 'cognitive neuroscience,language,aphasia', '0010-9452'),
('Brain and Language', 'Brain Lang', 'journal', 'P1', '神经语言学', 'https://www.sciencedirect.com/journal/brain-and-language', '月刊', 'neurolinguistics,fMRI,aphasia,language', '0093-934X'),
('Bilingualism: Language and Cognition', 'BLC', 'journal', 'P1', '双语研究', 'https://www.cambridge.org/core/journals/bilingualism-language-and-cognition', '季刊', 'bilingualism,second language,cognitive control', '1366-7289'),
('Applied Psycholinguistics', 'Appl Psycholinguist', 'journal', 'P1', '应用心理语言学', 'https://www.cambridge.org/core/journals/applied-psycholinguistics', '双月刊', 'applied psycholinguistics,language disorders,language acquisition', '0142-7164'),
('Frontiers in Psychology', 'Front Psychol', 'journal', 'P2', '心理学综合', 'https://www.frontiersin.org/journals/psychology', '持续更新', 'language sciences,psycholinguistics,cognitive psychology', '1664-1078'),
('PLOS ONE', 'PLoS ONE', 'journal', 'P2', '综合科学', 'https://journals.plos.org/plosone/', '持续更新', 'multiple disciplines,language,psychology', '1932-6203'),
('Quarterly Journal of Experimental Psychology', 'QJEP', 'journal', 'P2', '实验心理学', 'https://journals.sagepub.com/home/qjp', '月刊', 'experimental psychology,human cognition', '1747-0218'),
('Acta Psychologica', 'Acta Psychol', 'journal', 'P2', '实验心理学', 'https://www.sciencedirect.com/journal/acta-psychologica', '10期/年', 'experimental psychology,perception,attention', '0001-6918'),
('Journal of Experimental Psychology: General', 'J Exp Psychol Gen', 'journal', 'P2', '实验心理学综合', 'https://www.apa.org/pubs/journals/xge', '月刊', 'experimental psychology,general topics', '0096-3445'),
('Language Learning', 'Lang Learn', 'journal', 'P2', '语言习得', 'https://onlinelibrary.wiley.com/journal/14679922', '季刊', 'second language acquisition,language learning', '0023-8333'),
('Second Language Research', 'Second Lang Res', 'journal', 'P2', '二语习得', 'https://journals.sagepub.com/home/slr', '季刊', 'second language acquisition,research methods', '0267-6583'),
('Studies in Second Language Acquisition', 'SSLA', 'journal', 'P2', '二语习得', 'https://www.cambridge.org/core/journals/studies-in-second-language-acquisition', '季刊', 'second language acquisition,linguistics', '0272-2631'),
('Cognitive Science', 'Cognitive Sci', 'journal', 'P2', '认知科学', 'https://onlinelibrary.wiley.com/journal/15516709', '月刊', 'cognitive science,computational modeling', '0364-0213'),
('Annual Review of Linguistics', 'Annu Rev Linguist', 'journal', 'P2', '语言学综述', 'https://www.annualreviews.org/journal/linguistics', '年刊', 'linguistics review,language sciences', '2333-9683'),
('Linguistic Inquiry', 'Linguist Inq', 'journal', 'P2', '理论语言学', 'https://direct.mit.edu/ling', '季刊', 'theoretical linguistics,syntax', '0024-3892'),
('Natural Language & Linguistic Theory', 'Nat Lang Linguist Theory', 'journal', 'P2', '理论语言学', 'https://link.springer.com/journal/11049', '季刊', 'linguistic theory,syntax,phonology', '0167-806X'),
('Journal of Linguistics', 'J Linguist', 'journal', 'P2', '语言学', 'https://www.cambridge.org/core/journals/journal-of-linguistics', '季刊', 'linguistics theory,language', '0022-2267'),
('Language and Cognitive Processes', NULL, 'journal', 'P2', '语言认知', 'https://www.tandfonline.com/toc/plcp21/current', '10期/年', 'language processing,cognition', '0169-0965'),
('Language', 'Language', 'journal', 'P1', '语言学核心', 'https://www.linguisticsociety.org/lsa-publications/language', '季刊', 'linguistics theory,empirical studies', '0097-8507'),
('Attention, Perception, & Psychophysics', 'Atten Percept Psychophys', 'journal', 'P2', '感知觉', 'https://link.springer.com/journal/13414', '8期/年', 'attention,perception,psychophysics', '1943-3921'),
('Memory & Cognition', 'Mem Cognit', 'journal', 'P2', '记忆与认知', 'https://link.springer.com/journal/13421', '8期/年', 'memory,cognition,learning', '0090-502X'),
('Journal of Experimental Psychology: Learning, Memory, and Cognition', 'J Exp Psychol Learn', 'journal', 'P2', '学习与记忆', 'https://www.apa.org/pubs/journals/xlm', '月刊', 'learning,memory,cognition,language', '0278-7393'),
('CogSci Conference', 'CogSci', 'conference', 'P0', '认知科学会议', 'https://cognitivesciencesociety.org/', '年会更M', 'cognitive science,annual conference', NULL),
('AMLaP', 'AMLaP', 'conference', 'P0', '心理语言学会议', 'https://amlap.org/', '年会更M', 'language processing,psycholinguistics,annual conference', NULL),
('CUNY Conference on Human Sentence Processing', 'CUNY', 'conference', 'P0', '句子加工会议', 'https://www.cuny.edu/', '年会更M', 'sentence processing,psycholinguistics,annual conference', NULL),
('Psychonomic Society Annual Meeting', 'Psychonomic Society', 'conference', 'P1', '实验心理学会议', 'https://www.psychonomic.org/', '年会更M', 'cognitive psychology,psycholinguistics,annual conference', NULL),
('Annual Meeting of the Cognitive Science Society', 'CogSci 年会', 'conference', 'P1', '认知科学会', 'https://cognitivesciencesociety.org/', '年会更M', 'cognitive science,annual conference', NULL),
('Society for the Neurobiology of Language', 'SNL', 'conference', 'P1', '神经语言学会议', 'https://www.neurolang.org/', '年会更M', 'neurolinguistics,language,neuroscience,annual conference', NULL),
('International Congress of Linguists', 'ICL', 'conference', 'P2', '语言学大会', 'https://www.linguisticsociety.org/', '不定期', 'linguistics,international congress', NULL),
('Association for Computational Linguistics', 'ACL', 'conference', 'P2', '计算语言学', 'https://www.aclweb.org/', '年会更M', 'computational linguistics,NLP,annual conference', NULL),
('Linguistic Society of America Annual Meeting', 'LSA', 'conference', 'P2', '语言学会议', 'https://www.linguisticsociety.org/', '年会更M', 'linguistics,annual conference', NULL),
('European Conference on Eye Movements', 'ECEM', 'conference', 'P2', '眼动会议', 'https://www.ecem.info/', '两年一届', 'eye movements,eye tracking,reading', NULL);